/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package no.kommune.oslo.automatiserteprosesser.maskinporten

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
